name: task_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.1

flutter:
  uses-material-design: true

# 👇 THIS MUST BE OUTSIDE dev_dependencies
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"

  instructions:
    - assets:download
    - assets:extract
    - android:androidManifest
    - android:flavorizrGradle
    - android:buildGradle
    - android:dummyAssets
    - android:icons
    - flutter:flavors
    - flutter:app
    - flutter:pages
    - flutter:main
    - assets:clean
    - ide:config

  flavors:
    dev:
      app:
        name: "Task Manager Dev"
      android:
        applicationId: "com.spowerz.taskmanager.dev"
        applicationIdSuffix: ".dev"

    prod:
      app:
        name: "Task Manager"
      android:
        applicationId: "com.spowerz.taskmanager"